#!/bin/sh

CORRECT_NAME="Bobby Thomas Thomas"
CORRECT_EMAIL="bobbythomasthomas23@gmail.com"

export GIT_COMMITTER_NAME="$CORRECT_NAME"
export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
export GIT_AUTHOR_NAME="$CORRECT_NAME"
export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
